# Generated by Django 4.0.6 on 2022-07-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookauthor'),
    ]

    operations = [
    ]
